// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Class : int
{
 Base = 0,
 Player = 1,
 id = 2,
 test = 3,
 ping = 4,
 PlayerStat = 5,
 SendMeStat = 6,
 Monster = 7,
 MonsterStat = 8,
 LogIn = 9,
 FirstCharacterData = 10,
 fItem = 11,
 fInventory = 12,
 fEquipSlots = 13,
 fheader = 14,
 fReward = 15,
 fDamage = 16,
 fEquip = 17,
};

