// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fEquip : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fEquip GetRootAsfEquip(ByteBuffer _bb) { return GetRootAsfEquip(_bb, new fEquip()); }
  public static fEquip GetRootAsfEquip(ByteBuffer _bb, fEquip obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fEquip __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public int Weapon { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Weapon2 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Helm { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Armor { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<fEquip> CreatefEquip(FlatBufferBuilder builder,
      Class cType = Class.Base,
      int weapon = 0,
      int weapon2 = 0,
      int helm = 0,
      int armor = 0) {
    builder.StartObject(5);
    fEquip.AddArmor(builder, armor);
    fEquip.AddHelm(builder, helm);
    fEquip.AddWeapon2(builder, weapon2);
    fEquip.AddWeapon(builder, weapon);
    fEquip.AddCType(builder, cType);
    return fEquip.EndfEquip(builder);
  }

  public static void StartfEquip(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddWeapon(FlatBufferBuilder builder, int weapon) { builder.AddInt(1, weapon, 0); }
  public static void AddWeapon2(FlatBufferBuilder builder, int weapon2) { builder.AddInt(2, weapon2, 0); }
  public static void AddHelm(FlatBufferBuilder builder, int helm) { builder.AddInt(3, helm, 0); }
  public static void AddArmor(FlatBufferBuilder builder, int armor) { builder.AddInt(4, armor, 0); }
  public static Offset<fEquip> EndfEquip(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fEquip>(o);
  }
};

