// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fEquipSlots : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fEquipSlots GetRootAsfEquipSlots(ByteBuffer _bb) { return GetRootAsfEquipSlots(_bb, new fEquipSlots()); }
  public static fEquipSlots GetRootAsfEquipSlots(ByteBuffer _bb, fEquipSlots obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fEquipSlots __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public int Slot(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int SlotLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ArraySegment<byte>? GetSlotBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<fEquipSlots> CreatefEquipSlots(FlatBufferBuilder builder,
      Class cType = Class.Base,
      VectorOffset SlotOffset = default(VectorOffset)) {
    builder.StartObject(2);
    fEquipSlots.AddSlot(builder, SlotOffset);
    fEquipSlots.AddCType(builder, cType);
    return fEquipSlots.EndfEquipSlots(builder);
  }

  public static void StartfEquipSlots(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddSlot(FlatBufferBuilder builder, VectorOffset SlotOffset) { builder.AddOffset(1, SlotOffset.Value, 0); }
  public static VectorOffset CreateSlotVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartSlotVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fEquipSlots> EndfEquipSlots(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fEquipSlots>(o);
  }
};

