// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fIG_EffectPos : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fIG_EffectPos GetRootAsfIG_EffectPos(ByteBuffer _bb) { return GetRootAsfIG_EffectPos(_bb, new fIG_EffectPos()); }
  public static fIG_EffectPos GetRootAsfIG_EffectPos(ByteBuffer _bb, fIG_EffectPos obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fIG_EffectPos __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public int EftID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string EftName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetEftNameBytes() { return __p.__vector_as_arraysegment(8); }
  public float X { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<fIG_EffectPos> CreatefIG_EffectPos(FlatBufferBuilder builder,
      Class cType = Class.Base,
      int eftID = 0,
      StringOffset eftNameOffset = default(StringOffset),
      float x = 0.0f,
      float y = 0.0f,
      float z = 0.0f) {
    builder.StartObject(6);
    fIG_EffectPos.AddZ(builder, z);
    fIG_EffectPos.AddY(builder, y);
    fIG_EffectPos.AddX(builder, x);
    fIG_EffectPos.AddEftName(builder, eftNameOffset);
    fIG_EffectPos.AddEftID(builder, eftID);
    fIG_EffectPos.AddCType(builder, cType);
    return fIG_EffectPos.EndfIG_EffectPos(builder);
  }

  public static void StartfIG_EffectPos(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddEftID(FlatBufferBuilder builder, int eftID) { builder.AddInt(1, eftID, 0); }
  public static void AddEftName(FlatBufferBuilder builder, StringOffset eftNameOffset) { builder.AddOffset(2, eftNameOffset.Value, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(3, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(4, y, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(5, z, 0.0f); }
  public static Offset<fIG_EffectPos> EndfIG_EffectPos(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fIG_EffectPos>(o);
  }
};

