// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fIG_Effect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fIG_Effect GetRootAsfIG_Effect(ByteBuffer _bb) { return GetRootAsfIG_Effect(_bb, new fIG_Effect()); }
  public static fIG_Effect GetRootAsfIG_Effect(ByteBuffer _bb, fIG_Effect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fIG_Effect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public int PID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float X { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public string EftName { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetEftNameBytes() { return __p.__vector_as_arraysegment(14); }

  public static Offset<fIG_Effect> CreatefIG_Effect(FlatBufferBuilder builder,
      Class cType = Class.Base,
      int pID = 0,
      float x = 0.0f,
      float y = 0.0f,
      float z = 0.0f,
      StringOffset eftNameOffset = default(StringOffset)) {
    builder.StartObject(6);
    fIG_Effect.AddEftName(builder, eftNameOffset);
    fIG_Effect.AddZ(builder, z);
    fIG_Effect.AddY(builder, y);
    fIG_Effect.AddX(builder, x);
    fIG_Effect.AddPID(builder, pID);
    fIG_Effect.AddCType(builder, cType);
    return fIG_Effect.EndfIG_Effect(builder);
  }

  public static void StartfIG_Effect(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddPID(FlatBufferBuilder builder, int pID) { builder.AddInt(1, pID, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(2, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(3, y, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(4, z, 0.0f); }
  public static void AddEftName(FlatBufferBuilder builder, StringOffset eftNameOffset) { builder.AddOffset(5, eftNameOffset.Value, 0); }
  public static Offset<fIG_Effect> EndfIG_Effect(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fIG_Effect>(o);
  }
};

