// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fItemGet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fItemGet GetRootAsfItemGet(ByteBuffer _bb) { return GetRootAsfItemGet(_bb, new fItemGet()); }
  public static fItemGet GetRootAsfItemGet(ByteBuffer _bb, fItemGet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fItemGet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public int DID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Count { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<fItemGet> CreatefItemGet(FlatBufferBuilder builder,
      Class cType = Class.Base,
      int dID = 0,
      int count = 0) {
    builder.StartObject(3);
    fItemGet.AddCount(builder, count);
    fItemGet.AddDID(builder, dID);
    fItemGet.AddCType(builder, cType);
    return fItemGet.EndfItemGet(builder);
  }

  public static void StartfItemGet(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddDID(FlatBufferBuilder builder, int dID) { builder.AddInt(1, dID, 0); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(2, count, 0); }
  public static Offset<fItemGet> EndfItemGet(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fItemGet>(o);
  }
};

