// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fReward : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fReward GetRootAsfReward(ByteBuffer _bb) { return GetRootAsfReward(_bb, new fReward()); }
  public static fReward GetRootAsfReward(ByteBuffer _bb, fReward obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fReward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public int Exp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MonID { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<fReward> CreatefReward(FlatBufferBuilder builder,
      Class cType = Class.Base,
      int exp = 0,
      int MonID = 0) {
    builder.StartObject(3);
    fReward.AddMonID(builder, MonID);
    fReward.AddExp(builder, exp);
    fReward.AddCType(builder, cType);
    return fReward.EndfReward(builder);
  }

  public static void StartfReward(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddExp(FlatBufferBuilder builder, int exp) { builder.AddInt(1, exp, 0); }
  public static void AddMonID(FlatBufferBuilder builder, int MonID) { builder.AddInt(2, MonID, 0); }
  public static Offset<fReward> EndfReward(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fReward>(o);
  }
};

