// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct ping : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ping GetRootAsping(ByteBuffer _bb) { return GetRootAsping(_bb, new ping()); }
  public static ping GetRootAsping(ByteBuffer _bb, ping obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ping __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public long Time { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<ping> Createping(FlatBufferBuilder builder,
      Class cType = Class.Base,
      long time = 0) {
    builder.StartObject(2);
    ping.AddTime(builder, time);
    ping.AddCType(builder, cType);
    return ping.Endping(builder);
  }

  public static void Startping(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddTime(FlatBufferBuilder builder, long time) { builder.AddLong(1, time, 0); }
  public static Offset<ping> Endping(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ping>(o);
  }
};

