// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct SendMeStat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SendMeStat GetRootAsSendMeStat(ByteBuffer _bb) { return GetRootAsSendMeStat(_bb, new SendMeStat()); }
  public static SendMeStat GetRootAsSendMeStat(ByteBuffer _bb, SendMeStat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SendMeStat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Class CType { get { int o = __p.__offset(4); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public Class StatDataType { get { int o = __p.__offset(6); return o != 0 ? (Class)__p.bb.GetInt(o + __p.bb_pos) : Class.Base; } }
  public int ID { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SendMeStat> CreateSendMeStat(FlatBufferBuilder builder,
      Class cType = Class.Base,
      Class StatDataType = Class.Base,
      int ID = 0) {
    builder.StartObject(3);
    SendMeStat.AddID(builder, ID);
    SendMeStat.AddStatDataType(builder, StatDataType);
    SendMeStat.AddCType(builder, cType);
    return SendMeStat.EndSendMeStat(builder);
  }

  public static void StartSendMeStat(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddCType(FlatBufferBuilder builder, Class cType) { builder.AddInt(0, (int)cType, 0); }
  public static void AddStatDataType(FlatBufferBuilder builder, Class StatDataType) { builder.AddInt(1, (int)StatDataType, 0); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(2, ID, 0); }
  public static Offset<SendMeStat> EndSendMeStat(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SendMeStat>(o);
  }
};

